### ISSUE TITLE
在存在云盘的情况下，不能正常显示云盘的信息

### ISSUE THREAD

**Issue by willleeego** [opengers/vminfo#1]
（1）有个domain的硬盘情况如下：
[root@compute1 ~]# virsh domblklist instance-0000002c
Target        Source
vda           /var/lib/nova/instances/6c463f7d-eed6-468f-9095-4a3c796814ff/disk
vdb           /dev/disk/by-path/ip-172.16.10.203:3260-iscsi-iqn.2010-10.org.openstack:volume-aaac3415-a246-4cd1-9032-44e74b66d48f-lun-0

_**vdb是一个远端挂载的云盘**_

（2）执行vminfo，报错：

[root@compute1 ~]# vminfo 
qemu-img: Could not open '/dev/disk/by-path/ip-172.16.10.203': Could not open '/dev/disk/by-path/ip-172.16.10.203': No such file or directory

**Comment by opengers** [comment]
因为脚本测试环境是本地存储，因此存在云盘时候可能会有问题
你的vdb磁盘中间有":", vdb路径被截断后就剩"/dev/disk/by-path/ip-172.16.10.203"部分了，因此找不到

**Comment by willleeego** [comment]
笨方法改了下：
#89：qemu-img info $(echo $ii |awk -F '[:]' '{if(NF>2){print $2":"$3":"$4} else {print $2} }')

**Comment by willleeego** [comment]
显然，这个该法不严谨。

**Comment by opengers** [comment]
问题在于awk中的字段分隔符":"跟你的云盘路径冲突
![image](https://raw.githubusercontent.com/opengers/pic/master/vminfo/5.png)
像图中那样改下84,89行，将":"替换为"|"，应该就可以了，你再测试一下，后续我会更新代码

**Comment by willleeego** [comment]
是，这样改比较好。谢谢。
